Jahanzaib test branch
guardianstraining/lms pull request #32
Opened 2023-05-08 15:29 UTC by jehanxaibahmed

Instructor to User Chat

2023-05-08 15:51 UTC, guardianstraining requested changes

2023-05-08 15:51 UTC, guardianstraining commented on app/Http/Controllers/ChatRequestsController.php
> +        $conversation->last_time_message = now();
last_time_message is not needed

The timestamp attribute in the schema provides a created_at & updated_at column, so the updated_at column can be used in this case.

To keep the controller clean, firstOr create should replace line 53 - 69. See example below

 $conversation = Conversation::firstOrCreate(
            ['sender_id' => $senderId, 'receiver_id' => $receiverId ],
            ['chat_id' => $chatId]
        );

2023-05-08 15:51 UTC, guardianstraining commented on app/Http/Controllers/ChatRequestsController.php
> +            if ($chat_request->assigned_to_id !== intval($instructor_id)) {
Any specific reason for using intval?

2023-05-08 15:51 UTC, guardianstraining commented on resources/views/jambasangsang/backend/chat_requests/partials/show.blade.php
> +            <h6 class="mt-3 card-title">Subject: {!! $chat_request->issue !!} </h6>
Why are you using double exclamation?
Please understand the use case

2023-05-08 15:51 UTC, guardianstraining commented on resources/views/jambasangsang/backend/chat_requests/partials/show.blade.php
>                  <button id="payment-button" type="submit" class="btn btn-info btn-block">
rename payment button to match what's happening on this page

2023-05-08 15:51 UTC, guardianstraining commented on resources/views/jambasangsang/backend/live_chat/assign.blade.php
> +                <button id="payment-button" type="submit" class="btn btn-info btn-block">
payment button again

2023-05-08 15:51 UTC, guardianstraining commented on resources/views/layouts/backend/master.blade.php
> +    <script src="{{ asset('jambasangsang/backend/vendors/jquery/dist/jquery.min.js') }}"></script>
Did you add a new script? seems there's duplicate jquery.min.js on this page

2023-05-09 10:13 UTC, jehanxaibahmed commented on app/Http/Controllers/ChatRequestsController.php
> +        $conversation->last_time_message = now();
We are using this last_time_message in the conversation table and update it on every message sent while the update_at column is updated when we do some updates in the conversation table.

2023-05-10 10:04 UTC, guardianstraining approved these changes

2023-05-10 10:04 UTC, merged